### ISSUE TITLE
Using fzf with fd has surprising behaviour

### ISSUE THREAD

**Issue by skorokithakis** [jethrokuan/fzf#100]
I set the find command to fd, as in fzf's repo recommendation, and I am getting surprising behaviour when finding a file. Namely, when I am in `~/code/someproject/` and do `vim /tmp/<Ctrl+f>`, fzf starts up respecting the `.gitignore` file in the directory I am in, rather than the target directory, and displays no files in `/tmp` even though there are many.

I don't know if this is a problem with fzf or fzf-fish, so I figured I'd ask here first.

**Comment by skorokithakis** [comment]
Yes, this is my `config.fish`:

```
set FZF_FIND_FILE_COMMAND "fd --type f"
```

The problem is that `fd` gets launched in a way that makes it not work properly. I don't know what the exact command/directory/environment used to launch it is, so I couldn't test further, but if I do `fd tmp /tmp/`, I get a list of temp files.

Testing it now, if I do `vim /tmp/<Ctrl-f>` from the directory `~/code/someproject`, the autocomplete box shows me files in `~/code/someproject` rather than in `/tmp/`... Am I doing something wrong?

**Comment by jethrokuan** [comment]
I looked into it further, and you'd need to pass the variable `$dir` as a command, so something like:

`set -U FZF_FIND_FILE_COMMAND "fd --type f . \$dir" ` works.

Unfortunately, I don't see a way to abstract these details away from users, as `$dir` may appear in different places for different find_file commands.

**Comment by skorokithakis** [comment]
Ah, you are right, that fixes it! I thought the directory was somehow appended.

I don't care so much about abstraction (I can figure it out on my own), as much as I care for an example in the README that will point me to the right direction. Do you want me to open a PR with your line in it?

**Comment by jethrokuan** [comment]
Sounds good! Thanks for reporting.

**Comment by jethrokuan** [comment]
Closed with #102
