### ISSUE TITLE
If --height is included in FZF_COMPLETE, commandline is empty when cancel

### ISSUE THREAD

**Issue by ngyuki** [jethrokuan/fzf#103]
hi.
Thank you for awesome tool.

I customized `FZF_COMPLETE` as follows.

```
set FZF_COMPLETE "--cycle --reverse --inline-info --with-nth=1 --height=40% --multi --bind tab:down,btab:up,ctrl-space:toggle"
```

When close display of completion with ESC key, commandline is empty (but actually it is entered).

https://asciinema.org/a/cW3VkSotjUDrnnwrMyKIIc88Z

I think so, need `commandline -f repaint` here?
https://github.com/jethrokuan/fzf/blob/master/functions/__fzf_complete.fish#L76

**Comment by jethrokuan** [comment]
Hi, just fyi, FZF_COMPLETE was never meant to be used that way (see https://github.com/jethrokuan/fzf/wiki/FZF-Tab-Completions).

**Comment by ngyuki** [comment]
Sorry, I was misunderstanding by see https://github.com/jethrokuan/fzf/blob/master/functions/__fzf_complete.fish#L159-L160.
