### ISSUE TITLE
fish_vi_key_bindings disables FZF_COMPLETE

### ISSUE THREAD

**Issue by rbpatt2019** [jethrokuan/fzf#104]
Thanks for the excellent plugin! 

I've come across some odd behavior with the completion widget. If I set FZF_COMPLETE while fish_default_key_bindings is active, then tab completion works with FZF; however, if I activate fish_vi_key_bindings, tab completion reverts to normal Fish behavior. I should also note that this only effects tab completion. All keybindings, with FZF_LEGACY_KEYBINDINGS set to 0 or 1, are unaffected by any changes in fish_vi_mode_bindings.

I'm running Fish 3.0.0-1 in kitty 0.13.3-1 terminal emulator. Arch Linux build with i3 v4.16.1-1.

**Comment by jethrokuan** [comment]
Hi, could you run `bind -M insert \t '__fzf_complete'` and see if that resolves your issue? If so, I can push up a fix.

**Comment by rbpatt2019** [comment]
Just tested it. Works like a charm now!
Feel free to close this issue. Thanks!

**Comment by jethrokuan** [comment]
Should be fixed in master! Thanks for reporting @rbpatt2019 !
