### ISSUE TITLE
Keybindings are not loaded when installing with omf

### ISSUE THREAD

**Issue by PierreRust** [jethrokuan/fzf#109]
When installing fzf plugin using omf, the keybinding are not activated .

When loading a plugin, omf looks for keybindings in ``pkg/*/key_bindings.fish``. From omf's init.fish :  

```
  # Prepare packages key bindings paths
  set -l key_bindings $OMF_CONFIG/key_binding?.fish \
                      {$OMF_CONFIG,$OMF_PATH}/pkg/*/key_bindings.fish \
                      {$OMF_CONFIG,$OMF_PATH}/themes/$theme/key_binding?.fish
```

In this package the bindings are defined in ``pkg/fzf/conf.d/fzf_key_bindings.fish `` and this omf does not find them.

Note: the issue is similar to #101 where it has been finally "solved" by using fisher instead of omf.

**Comment by jethrokuan** [comment]
Hi @PierreRust ,

omf supposedly added support for loading scripts in conf.d: https://github.com/oh-my-fish/oh-my-fish/issues/646

so it should work for omf users now too, could you check if you have the latest omf?

**Comment by PierreRust** [comment]
You're right, it actually works using dev channel.

I thought I had the latest omf, but it appears the support for ```conf.d``` is only in the dev channel, not in stable.

**Comment by jethrokuan** [comment]
Thanks for checking. Closing this issue, because I'm not inclined to making changes for current omf
