### ISSUE TITLE
"Non-legacy" keybindings conflict with defaults in fish v3

### ISSUE THREAD

**Issue by benjamineskola** [jethrokuan/fzf#119]
Setting `FZF_LEGACY_KEYBINDINGS` to 0 will create a keybinding for ctrl-f to `__fzf_find_file`. However, by default ctrl-f is bound to `forward-word`, which also triggers the autosuggestion feature.

Workarounds are either to use the right arrow key (although this may not work on all terminals, and I often hit ctrl-f out of habit) or to leave the `FZF_LEGACY_KEYBINDINGS` set to the default (which conflicts with other bindings, but they may be less important ones).

This isn't a major issue at all, but it would be nice to be able to use the fzf bindings and not to conflict with any of the defaults.

**Comment by jethrokuan** [comment]
I use Emacs, and face this issue as well. Could you recommend a set of replacement keybindings? I haven't been able to think of any that's both mnemonic and avoids keybinding conflicts. I think it makes sense here to leave it up as an RFC, and merge it if there aren't any major objections.

**Comment by benjamineskola** [comment]
I took a quick look at the default keybindings and it doesn’t seem like there are many free control-keys: ^G ^H ^I ^J ^M ^O ^Q ^R ^Z. Of these, ^H, ^I, ^M, ^Q, ^Z are likely to conflict with default terminal bindings, and ^G ^O ^R are used by fzf already, which only leaves ^J.

For the alt-keys, alt-a alt-g alt-i alt-j alt-k alt-m alt-n alt-o alt-q alt-r alt-s alt-x alt-z are free, and only alt-o is used by fzf.

Since fzf uses ^O, ^G, and alt-o, perhaps using alt-g for this would make some sense? It’s not especially mnemonic on its own, but perhaps the relationship to the others might help.

**Comment by jethrokuan** [comment]
I'm looking at
https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_default_key_bindings.fish

The default readline bindings are supported, let's try to avoid
overriding those.

How about using `Ctrl-g` for finding a file, and `Alt-g` for opening
it with the "alternative method" i.e. xdg-open?

I feel like if we're going with this scheme `Ctrl-o` doesn't fit
anymore: The other `-o` ones deal with changing directories.

| New Keybindings | Remarks                                         | Changed |
| --------------- | ----------------------------------------------- | ------- |
| Ctrl-g          | Find a file.                                    | Yes     |
| Ctrl-r          | Search through command history.                 | No      |
| Alt-o           | cd into sub-directories (recursively searched). | No      |
| Alt-Shift-o     | cd into sub-directories, including hidden ones. | No      |
| Ctrl-o          | Open a file/dir using default editor ($EDITOR)  | No      |
| Alt-g           | Open a file/dir using xdg-open or open command  | Yes     |

**Comment by benjamineskola** [comment]
Perhaps opening a file/dir with $EDITOR can be alt-g, and opening it with xdg-open can be alt-shift-g?

**Comment by jethrokuan** [comment]
How about swapping o and g around to make it more mnemonic?

o - open a file
g - go to a directory

| New Keybindings | Remarks                                         | Changed |
| --------------- | ----------------------------------------------- | ------- |
| Ctrl-o          | Find a file.                                    | Yes     |
| Ctrl-r          | Search through command history.                 | No      |
| Alt-g           | cd into sub-directories (recursively searched). | Yes      |
| Alt-Shift-g     | cd into sub-directories, including hidden ones. | Yes      |
| Alt-o          | Open a file/dir using default editor ($EDITOR)  | Yes      |
| Alt-Shift-o           | Open a file/dir using xdg-open or open command  | Yes     |

**Comment by benjamineskola** [comment]
I think that makes the most sense, yes. (It does have the downside of being a bigger change for existing users, though.)

**Comment by jethrokuan** [comment]
I merged #12 that should address this
