### ISSUE TITLE
binding does not use proper command

### ISSUE THREAD

**Issue by DaniloZZZ** [jethrokuan/fzf#121]
When trying to change both command and keybinding the command dont change. 

```
bind \; '__fzf_cd --hidden'

set -U FZF_CD_COMMAND  "fd --type d ."
```

**Comment by jethrokuan** [comment]
You'll need to run `set -U FZF_CD_WITH_HIDDEN_COMMAND "fd --type d -H ."` instead, hope that works for you.

**Comment by DaniloZZZ** [comment]
This works, thanks.
How to bind \c;  (ctrl+semicolon)? How to bind win(super) key?

**Comment by jethrokuan** [comment]
Not sure how to bind `\c\;`, seems to bind fine but can't trigger fzf with it. I'm not sure shells recognize the super key, afaik you'll need to do some key emulation tricks.
