### ISSUE TITLE
Doesn't work with omf

### ISSUE THREAD

**Issue by alfa07** [jethrokuan/fzf#123]
OMF expects the following dir structure:
```
functions/
completions/
bundle
init.fish
key_bindings.fish
```
which is not the case for this package.
This leads to only functions being loaded. No keybindings or fzf.fish

**Comment by jethrokuan** [comment]
I should add some documentation for OMF users, but see https://github.com/jethrokuan/fzf/issues/109 for the solution

**Comment by alfa07** [comment]
Switched to fisher :)
