### ISSUE TITLE
Sorting of complete list is hard coded 

### ISSUE THREAD

**Issue by tonico** [jethrokuan/fzf#126]
The [complete](https://fishshell.com/docs/current/commands.html#complete) command has the option `--keep-order` to preserve the order of its option arguments. This is used, for example, in the [completion for the j command](https://github.com/fish-shell/fish-shell/blob/master/share/completions/j.fish). When using fzf complete, the `--keep-order` option has no effect because the sorting of the complete list in [functions/__fzf_complete.fish](https://github.com/jethrokuan/fzf/blob/46a3392f88735af690ea448ecb89344dc95045d7/functions/__fzf_complete.fish#L61) is currently hard coded:

        string join -- \n $complist \
        | sort \
        | eval (__fzfcmd) (string escape --no-quoted -- $initial_query) --print-query (__fzf_complete_opts) \
        | ...

Since `complete -C$cmd`  is sorted alphabetically by default, i.e., if `--keep-order` was not set, I think the simplest solution is to remove the `sort` command from the pipe.

**Comment by jethrokuan** [comment]
I think that's reasonable.

**Comment by jethrokuan** [comment]
Should be resolved now, feel free to reopen if you have any issues!
