### ISSUE TITLE
Tab completion is incompatible with laughedelic/pisces

### ISSUE THREAD

**Issue by lukasbindreiter** [jethrokuan/fzf#134]
It seems that the tab completion key binding is incompatible with the fish plugin: https://github.com/laughedelic/pisces

![9rF4h47Atf](https://user-images.githubusercontent.com/21131639/71187843-292a0780-2280-11ea-82eb-842ae8f11949.gif)

To be honest I'm not completely sure whether or not this is an issue of this plugin or of `pisces`, maybe someone knows what exactly is going on?

Note: I'm using `FZF_COMPLETE 2`, but I tried the other options as well and they also didn't work.

**Comment by jethrokuan** [comment]
`pisces` also overrides the tab key, so I'd say you'd have to choose one or the other.
