### ISSUE TITLE
 jethrokuan/fzf does not seem to work with fish 3.1.1 

### ISSUE THREAD

**Issue by OakNinja** [jethrokuan/fzf#147]
👋 

I've tried to find out why my shell was acting strange, and it seems like this package does not work with fish 3.1.1. Or I'm doing something wrong. I upgraded fish yesterday and all shortcuts stopped working, I removed all of my local fish config and reinstalled everything but did not resolve my issues until I downgraded to fish 3.1.0.

I'm looking into this as well, but I guess this issue might be caused by 3.1.1 as well: https://github.com/jethrokuan/fzf/issues/145

**Comment by amir20** [comment]
I have also filed this bug on tzt at https://github.com/junegunn/fzf/issues/2008

**Comment by OakNinja** [comment]
This will be fixed in 3.1.2 according to https://github.com/fish-shell/fish-shell/issues/6955#

I’ll close this issue when 3.1.2 is live.

**Comment by OakNinja** [comment]
Verified working in 3.1.2.
