### ISSUE TITLE
Newest fish shell update broke this.

### ISSUE THREAD

**Issue by dessalines** [jethrokuan/fzf#148]
This plugin isn't working right now with fish v3.1.1

**Comment by vale981** [comment]
What is not working? For me it just hangs.

**Comment by jethrokuan** [comment]
This was reported previously in #147 , v3.1.2 seems to have fixed it.

**Comment by dessalines** [comment]
Ah, I tried updating this plugin with omf, but it didn't seem to have an update yet.
