### ISSUE TITLE
Completion binding doesn't work

### ISSUE THREAD

**Issue by kidonng** [jethrokuan/fzf#167]
Tested on latest stable Fish (3.1.2) and master branch on iTerm, as well as latest stable Fish on Termux. Both installed jethrokuan/fzf with latest Fisher.

[The code](https://github.com/jethrokuan/fzf/blob/2bac3bbc1014d90eece973e4f3daa5571f5288a3/conf.d/fzf_key_bindings.fish#L36-L41) runs, but it doesn't bind the Tab key. Changing it to something else doesn't work either. Binding it manually or in `~/.config/fish/config.fish` works though.

**Comment by jorgebucaran** [comment]
@kidonng What other plugins are you currently using?

**Comment by kidonng** [comment]
It's laughedelic/pisces#10, sorry!

**Comment by be4zad** [comment]
Also won't work with [jorgebucaran/autopair.fish](https://github.com/jorgebucaran/autopair.fish)

**Comment by jorgebucaran** [comment]
Note that autopair.fish [binds the tab key](https://github.com/jorgebucaran/autopair.fish/blob/4d1752ff5b39819ab58d7337c69220342e9de0e2/conf.d/autopair.fish#L18).
