### ISSUE TITLE
Keybindings not working anymore with vi or hybrid bindings

### ISSUE THREAD

**Issue by ybc37** [jethrokuan/fzf#171]
Hi!

Since 3fb7ed9, the keybindings are no longer set up in certain cases:

* It doesn't work with `fish_hybrid_key_bindings`, because the new condition only checks for `fish_vi_key_bindings`.
* It doesn't work anymore when setting `fish_key_bindings` instead of calling `fish_(vi|hybrid)_key_bindings` directly, e.g. `set -g fish_key_bindings fish_vi_key_bindings` (example in the docs: https://fishshell.com/docs/current/cmds/bind.html#examples, https://fishshell.com/docs/current/#command-line-editor).

Sorry for not sending a PR directly, but I don't have much time right now and also thinking about just using fzf built-in fish integration anyway :) I hope the issue helps anyway and maybe I'll submit a PR at some point.

**Comment by jorgebucaran** [comment]
Ping @rodrigobdz.

**Comment by jorgebucaran** [comment]
@ybc37 I'd be happy to revert 3fb7ed9, but I need @rodrigobdz's input first to find out what happened here.

**Comment by rodrigobdz** [comment]
@jorgebucaran Sure, let me check this out and I'll get back to you later today

**Comment by rodrigobdz** [comment]
Alright, I get @ybc37's point that the if-condition is only checking for `fish_vi_key_bindings` to be set and not for `fish_hybrid_key_bindings`, which are the two possible cases in which the if-condition should be evaluated to `true`. 

Thus, the correct if-condition in this case should check if any non-default keybinding is used. My proposal:

```diff
- if test "$fish_key_bindings" = fish_vi_key_bindings
+ if ! test "$fish_key_bindings" = fish_default_key_bindings
```

**Comment by jorgebucaran** [comment]
Want to send another PR?

**Comment by rodrigobdz** [comment]
Please help review the PR above

**Comment by ybc37** [comment]
Thanks so much @rodrigobdz and @jorgebucaran!
