### ISSUE TITLE
Commit 5a72cd0 has broken file path with fisher

### ISSUE THREAD

**Issue by MaxMilton** [jethrokuan/fzf#78]
As a result of the new `init.fish` file introduced in commit https://github.com/jethrokuan/fzf/commit/5a72cd07c3d71441725474236be8e0a04bb9cffd I'm getting errors printed to the console:

```
source: Error encountered while sourcing file “/home/max/.config/fish/conf.d/conf.d/fzf.fish”:
source: No such file or directory
```

If I manually change:

```fish
source (dirname (status --current-filename))/conf.d/fzf.fish
```

to:

```fish
source (dirname (status --current-filename))/fzf.fish
```

then things work as expected. Not sure if it has anything to do with this but I've installed the package via fisher.

**Comment by jethrokuan** [comment]
Resolved by #77, more discussion in #76, thanks for reporting!
