### ISSUE TITLE
fzf only works after running fisher

### ISSUE THREAD

**Issue by nathan-gilbert** [jethrokuan/fzf#86]
I'm running iTerm2, installed the fzf plugin using fisherman 3.0.8. Whenever opening a new terminal, I can only use fzf after running `fisher` once. Any thoughts on what this could be? The init or key binding file not being read on startup?

**Comment by jethrokuan** [comment]
yeah, it's probably due to v3 not being supported yet, we'll have to wait for https://github.com/jethrokuan/fzf/pull/85 to get merged in.

**Comment by nathan-gilbert** [comment]
Ah, thank you. Didn't see that V3 was supported initially. I'll close this issue. Thanks for the response.
