### ISSUE TITLE
FZF_REVERSE_ISEARCH_COMMAND does not exist

### ISSUE THREAD

**Issue by neersighted** [jethrokuan/fzf#91]
Just a note that this variable is incorrectly listed in the README. It should likely be removed.

**Comment by neersighted** [comment]
This also appears to apply to `FZF_FIND_AND_EXECUTE_COMMAND`.

**Comment by jethrokuan** [comment]
Thanks for pointing it out! It used to be that a different command would be used for history since fish versions up to 2.4.0 was supported, but I must've changed it forgetting that was the case. And now with #88 , we support up to 2.6.0, so all's good.
