### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Memphizzz** [jethrokuan/fzf#94]
Hi,

when installing fzf from git, which options do I have to enable/disable for your plugin to work?
I tried going with yes for everything and then install this plugin through omf, but unfortunately the keybindings stay on legacy even though I "set -U FZF_LEGACY_KEYBINDINGS 0". Also tab-completion didn't start working.

Any Ideas?

**Comment by jethrokuan** [comment]
Sorry I've been really busy with other commitments. Up until recently, omf didn't support loading from `conf.d` (https://github.com/oh-my-fish/oh-my-fish/issues/646), so stuff like keybindings wouldn't work in omf. There's a fix now, so you may have to run the dev channel of omf, or wait till it reaches mainline.

**Comment by Memphizzz** [comment]
No problem. Thanks for the reply. I see, I'll just wait a bit then :)
