### ISSUE TITLE
Setting set -U FZF_COMPLETE 0 doesn't disable tab completion

### ISSUE THREAD

**Issue by dmitriyK1** [jethrokuan/fzf#96]
Hi!
I noticed that when I'm setting `set -U FZF_COMPLETE 0` it doesn't disable tab completion, so I need to unset FZF_COMPLETE variable altogether

I noticed that here https://github.com/jethrokuan/fzf/blob/master/conf.d/fzf_key_bindings.fish#L35 you are checking for existence of this variable, would be nice to check it's value as well I guess

**Comment by jethrokuan** [comment]
Apologies on the poor documentation. `FZF_COMPLETE` is not a "boolean variable" (i.e. not just 1 or 0), and `$FZF_COMPLETE` set to 0 is still using `fzf` for tab completions.

See #98, and https://github.com/jethrokuan/fzf/wiki/FZF-Tab-Completions for more details.

**Comment by dmitriyK1** [comment]
@jethrokuan Thanks, I didn't see this!
